### ISSUE TITLE
Daftsex - Resolve Failed Daxab

### ISSUE THREAD

**Issue by DaveyK100** [dobbelina/repository.dobbelina#527] opened 2021-05-28 22:04 UTC
### Bug reports:

A lot of the videos on DaftSex fail due to the below error.

                 RESOLVE FAILED
 DAXAB LINK COULD NOT BE RESOLVED

### OS environment
What OS, Device, version etc

This error is on Windows and Android

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by Gujal00** [comment] 2021-05-29 00:16
Unable to replicate. post debug log of a non working link.

**Comment by DaveyK100** [comment] 2021-05-30 22:03
Hi Gujal00,

Please find log attached.
[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/6566976/kodi.log)

**Comment by Gujal00** [comment] 2021-05-30 23:39
unfortunately that is not a debug log so not useful.
Need FULL Debug log, not snippets

**Comment by DaveyK100** [comment] 2021-05-30 23:56
Hey, This is the full debug attached. 

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/6567083/kodi.log)

**Comment by Gujal00** [comment] 2021-05-31 04:21
I tested it on my Android Phone which runs Android 9 64bit same as your nVidia Shield and it works fine

From what I can see in your log, it looks like you upgraded from Kodi 18 to Kodi 19 as there are lot of kodi 18 script modules present. This could be a reason why it doesnt work for you. Kodi 19 needs to be a clean install and not an upgrade as it moves to Python3 from Python2, lot of old modules which dont work in Python3, still stay in the system and cause weird issues.

My suggestion would be to wipe the kodi application data from the Android-Settings-Applications menu and configure it fresh.

**Comment by DaveyK100** [comment] 2021-05-31 09:25
Hi Gujal00,

I have done a wipe and fresh install only Python3 shows on the Debug log now and I'm still getting an error so I tried another video and the same error appears. Log is attached I also tried this on my Windows PC and get the same error.

It looks like the website link is fine but the Daxab link has no working file. As I have checked working links and when you go to the Daxab link they actually have a playable video.

[kodi-Android.log](https://github.com/dobbelina/repository.dobbelina/files/6569271/kodi-Android.log)

**Comment by 12asdfg12** [comment] 2021-05-31 13:29
The videos from the log files don't play on the website either.


![image](https://user-images.githubusercontent.com/48175015/120200670-40b73f00-c22d-11eb-8dde-df85434d5d79.png)
![image](https://user-images.githubusercontent.com/48175015/120199456-ed90bc80-c22b-11eb-9e3b-3cb137c30909.png)

**Comment by DaveyK100** [comment] 2021-05-31 13:40
Working for me.

![image](https://user-images.githubusercontent.com/5904669/120202003-f8445500-c21d-11eb-88f4-10ec75b85782.png)

![image](https://user-images.githubusercontent.com/5904669/120202096-1447f680-c21e-11eb-9fe0-a5d0a0189496.png)

**Comment by DaveyK100** [comment] 2021-05-31 13:44
I think I just figured out why its not working for you,

You need the Daxab Ultimate extension installed to be able to play them. otherwise it won't play.

**Comment by 12asdfg12** [comment] 2021-05-31 13:55
Yes it works with the extension, the problem is the videos are hosted on vk (vkuservideo.net) servers not daxab.com.

**Comment by DaveyK100** [comment] 2021-05-31 14:01
So any video that's not on a daxab server won't work on the addon?

**Comment by 12asdfg12** [comment] 2021-05-31 14:07
yes

**Comment by DaveyK100** [comment] 2021-05-31 14:09
ok did that all change when Daftsex went down as all these links played fine on the addon before that happened.

**Comment by 12asdfg12** [comment] 2021-05-31 14:15
Probably something changed on the website since the videos don't play without the extension.

**Comment by Gujal00** [comment] 2021-06-01 02:36
@12asdfg12 @DaveyK100 
Thanks for the debugs, so there is all new method in daxab for the newer vk embeds

I have updated daxab.py in  https://github.com/jsergio123/script.module.resolveurl/commit/14eb6f3f13a3043eb377e4a1810f93221822f8c2, you can test it with that if you get that file from ResolveURL git and replace in your install

Let me know if still issues

**Comment by Gujal00** [comment] 2021-06-11 23:07
@DaveyK100 please close the issue if it is resolved

**Closed** 2021-06-12 07:38 UTC
