### ISSUE TITLE
Pornhub not working

### ISSUE THREAD

**Issue by spencer1234** [dobbelina/repository.dobbelina#199] opened 2020-03-01 20:41 UTC
When choosing Tubes -> Pornhub the movie list is completely empty.
The same happens when you go to categories.
In fact the categories are shown but with no content.

**Comment by dobbelina** [comment] 2020-03-02 07:21
Issue confirmed.

**Comment by DJMix-I-Can** [comment] 2020-03-02 15:11
[pornhub.zip](https://github.com/dobbelina/repository.dobbelina/files/4276101/pornhub.zip)
I was going to push a fix but I'm having trouble with it, so I attached the pornhub.py file. Fixed it.

**Comment by spencer1234** [comment] 2020-03-03 06:14
Thank you very much, I will test it when I'm back from work.

**Comment by spencer1234** [comment] 2020-03-03 16:18
Hi, the new file works like a charm.

Thank you very much for your very fast support.

**Comment by DJMix-I-Can** [comment] 2020-03-03 20:45
YW...

**Comment by rocket0612** [comment] 2020-03-03 21:50
Search isn't working ☹️

**Comment by DJMix-I-Can** [comment] 2020-03-04 02:17
Looks like they changed it, i tested it yesterday. Ok @12asdfg12 & @jdoedev123, I see where the search error is but don't know how to implement it. The main page list uses the following code,
main_block = re.compile('nf-videos videos search-video-thumbs[^>]+>(.*?)<div class="reset">', re.DOTALL).findall(listhtml)[0]
When you do a search, you get an error because the main list code is not the same, it uses this code main_block = re.compile('nf-videos[^>]+>(.*?)<div class="reset">', re.DOTALL).findall(listhtml)[0] 
It's not the same as the main list, I don't know how to add it. I was trying to learn it but going through this hiring process, so I really haven't had the chance to learn more.
Thanks.

**Comment by 12asdfg12** [comment] 2020-03-04 15:19
This line works for both main page and search

`    main_block = re.compile('search-video-thumbs(.*?)<div class="reset">', re.DOTALL).findall(listhtml)[0]`

**Comment by DJMix-I-Can** [comment] 2020-03-04 15:34
Yup that did it, thanks @12asdfg12 . Here goes the fix guys...
[pornhub.zip](https://github.com/dobbelina/repository.dobbelina/files/4288127/pornhub.zip)

**Comment by imurreflection** [comment] 2020-03-04 17:29
Hi DJMix-I-Can. Thank you so much for fixing this. However, please note that the final py file for pornhub when copied to UWC manually, it crashes the addon but when I take your first py file and then manually add 12asdfg12 line ,addon works fine and pornhub and the search works flawlessly.  Thank you again.

**Comment by spencer1234** [comment] 2020-03-04 17:35
Hi imurreflection,

you need to delete the corresponding pyo file and then replace the py file.
The pyo file get‘s recreated.

Then UWC works fine.

**Comment by imurreflection** [comment] 2020-03-04 19:08
But mate if I delete the corresponding py file then it won't get replaced. However, I will wait for dobbelina to release the update.

**Comment by spencer1234** [comment] 2020-03-04 19:12
Hi,

just delete the following files:

**pornhub.py
pornhub.pyo**

Then copy the new released pornhub.py into the folder.

The file pornhub.pyo will then be recreated and the search is working again.

**Comment by DJMix-I-Can** [comment] 2020-03-04 19:18
@imurreflection I just fired up my desktop, opened up github & downloaded that exact file.. I extracted it & copied it over to the sites folder. Fired up Kodi, which I haven't used in months and tested pornhub. It's working. BTW Even though you delete pornhub.py file, it's still going to be replaced with the new one.

**Comment by dobbelina** [comment] 2020-03-04 21:04
Thanks for the fix, merged #202

**Closed** 2020-03-09 07:22 UTC
Labels: fixed
