### ISSUE TITLE
Xhamster and pornhub issues

### ISSUE THREAD

**Issue by guyexotico** [dobbelina/repository.dobbelina#498] opened 2021-04-25 18:11 UTC
Xhamster does not load and pornhub links are not working.

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by Gujal00** [comment] 2021-04-25 19:29
duplicate of #491 and #493

**Comment by dobbelina** [comment] 2021-04-25 22:40
Closing duplicate

**Closed by dobbelina** 2021-04-25 22:40 UTC
