### ISSUE TITLE
Cumination Release

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#389] opened 2021-01-02 17:52 UTC
# Welcome to Cumination!
Matrix and Leia compatible release
Backup favorites from UWC can be imported.

Happy New Year From Team Cumination! 🚀

**Comment by TarkusLV** [comment] 2021-01-02 17:58
Awesome!  Can't wait to check it out.  Thanks to all for their efforts.

I see there is also a new version of the repository (presumably to handle this).

**Comment by imurreflection** [comment] 2021-01-02 19:35
Hi, I am slightly confused. Is cumination replacement of UWC? I can't see many sites available in UWC. Moreover, your repo doesn't have UWC. Please advise.

**Comment by TarkusLV** [comment] 2021-01-02 20:16
Restore Favorites doesn't work for me.  Says it's an invalid backup file.  Tried two different backups.  Is it the same format, so a manual restore would work? 

I really like that it seems to be built from the ground up for customization, even if that requires a little work to set it up initially to somewhat mimic UWC.  I do wish that Move to Top would make its way to Favourites, as I've already been spoiled by that change.  It's cool to be able to move up and down, but that doesn't replace Move to Top.

**Comment by TarkusLV** [comment] 2021-01-02 20:34
I know Cumination/UWC 1.2.42 is said to be Leia/Matrix compatible (and I've successfully tested on both), but I would also like to install one or both on SPMC (Krypton), but they won't install because of a script.module.websocket error.  Is that only compatible with Leia and above?

**Comment by Gujal00** [comment] 2021-01-02 21:35
@TarkusLV Cumination is Matrix/Leia only

UWC 1.2.42 is not Matrix compatible and should install on Krypton

**Comment by Kodionpi** [comment] 2021-01-02 22:04
Thanks for all your hard work to prepare the addon for the future Kodi versions +  new features!!!

"Restore Favorites" works for me, but restoring keywords-->  "invalid backup file" is displayed. 

The "set this view as default" option is very nice. Is it possible that two exceptions can be made from this default view? Main menu and search terms/keywords?

Thanks guys!!

+Pornhub is working again!

**Comment by TarkusLV** [comment] 2021-01-02 22:05
@Gujal00 
I get the same script.module.websocket error when trying to upgrade to UWC 1.2.42 on SPMC.  I have no problem running previous versions.

@dobbelina 
To add to my previous report about not being able to restore favorites, I'm able to on Windows, but not on my Firesticks.

**Comment by Gujal00** [comment] 2021-01-02 22:45
@TarkusLV 
UWC 1.2.42 release is not required for you as it is actually installing cumination. As far as I can see there are no other differences between 1.2.42 and 1.2.41. You can stay on 1.2.41 on SPMC

**Comment by onknight** [comment] 2021-01-03 00:49
It won't install on Any of my Version kodi 18.9 or 19 Beta 2 
even the Repo won't install on my PC

**Comment by TarkusLV** [comment] 2021-01-03 02:00
@Gujal00 
So does that mean UWC development has stopped?  I'm fine staying on 1.2.41, because it works well right now.  But in the future it may not, which is why I asked about that error.  I don't expect older versions of Kodi to be directly supported, but if it's something simple to fix that error, perhaps it would work.  Thanks.

**Comment by Gujal00** [comment] 2021-01-03 02:32
@TarkusLV I have no idea about the plans for uwc as I am not the developer. I maintain ResolveURL which is used by both UWC and Cumination. From what I can see script.module.websocket as used by cumination is only available on Leia and Matrix repos. No one can add that to the previous repos as Team Kodi stopped accepting new modules for any versions older than Leia

**Comment by dobbelina** [comment] 2021-01-03 04:25
> 
> 
> Thanks for all your hard work to prepare the addon for the future Kodi versions + new features!!!
> 
> "Restore Favorites" works for me, but restoring keywords--> "invalid backup file" is displayed.
> 
> The "set this view as default" option is very nice. Is it possible that two exceptions can be made from this default view? Main menu and search terms/keywords?
> 
> Thanks guys!!
> 
> +Pornhub is working again!

@Kodionpi 
**Settings=>General=>Enable custom** view types  de-select.

**Comment by onknight** [comment] 2021-01-03 05:21
When I try to install the new repository it gives me an invalid structure error on Kodi 19 beta 2 I can run everything off of that
when try install the Cumination add-on I get websock Library Failed

**Comment by Kodionpi** [comment] 2021-01-03 11:15
Thanks @dobbelina   The main menu/main page is now permanently displayed as a list. The pages with the video are almost all displayed with "Thumbnail View" (Kodi skin related). -But on some pages the "default view" is not applied. As an example, when I also go HQ, on the first page the "thumbnail view" is displayed with the videos. -as well as on the following pages. (as it should be), but on pages further back sometimes the list comes back. -When I change it manually, it stays like that. -but a little strange. 

One problem remains. The search terms/keywords that can be accessed through the search function on each page always take over the "thumbnail view" of the video from the page before. -no matter how often I change them manually. -they always reset.

**Comment by TarkusLV** [comment] 2021-01-03 16:09
@Gujal00 
The SPMC version I'm using (17.6a2) is Krypton based.  But alas, still too old, apparently.

@dobbelina 
Saving a Chaturbate category, such as Female or Couple, to the Main Menu or a Custom List doesn't work.  It gets saved alright, but produces an error when trying to open.  Other cam sites, such as Bongacams and Cam4, work as expected, however, when opening one of their categories directly from a custom list.

Possibly related, a couple times when trying to open a Chaturbate category from the main Chaturbate menu, I get the spinning wheel of death, where the busy indicator spins indefinitely.  If I try to back out, Kodi freezes and has to killed.  Most of the time it works fine, but occasionally it does not.

BTW, love the new graphics, and it's cool displaying the ages in the title for most cam models, and not just Chaturbate!

**Comment by nrk666** [comment] 2021-01-03 22:22
Hey, I'm the one who first asked about Kodi19/Pyhon3 (the other discussion issue) and this is great, looks like no interruption when Matrix comes out. I just want to say thanks.

**Comment by onknight** [comment] 2021-01-03 22:50
No my free cams  will that be added ?

**Comment by atreyuhere** [comment] 2021-01-04 14:53
First, thank you for the work you put I to this and best wishes to all!
Setting a download location and opening the downloads folder in the addon locks up Kodi.

**Comment by ErosVece** [comment] 2021-01-04 15:13
Adding Chaturbate to custom lists will be fixed in the next update :)

**Comment by TarkusLV** [comment] 2021-01-04 15:46
Found a bug:
Create Custom1 list and populate it.
Create Custom2 list and then from the context menu, move it up above Custom1.
Custom2 now has the contents of Custom1, while Custom1 is empty.  Move it back down, and Custom1 becomes populated again, while Custom2 becomes empty again.

**Comment by ErosVece** [comment] 2021-01-04 16:04
That is not a bug, but an hidden feature :) 

Thanks for reporting.

**Comment by onknight** [comment] 2021-01-04 17:13
This is one 1st working Kodi 19 Addons we have a lot to be proud of ..
I've seen a lot guys are going update there addons for 19 cause change over to Python 3
so bravo for this addon

**Comment by Gujal00** [comment] 2021-01-06 04:01
@onknight Videodevil has been working under matrix for over six months now

**Comment by atreyuhere** [comment] 2021-01-06 07:34
V1.1.2 -- setting and entering download folder still crashes kodi.

**Comment by Gujal00** [comment] 2021-01-06 08:36
@atreyuhere Seems to be happening only for you, so need a full debug log

**Comment by atreyuhere** [comment] 2021-01-06 09:47
@Gujal00 Did another test with a clean install on a testmachine with debugging enabled. Now this issue does not occur.
Weird, i tested on three different systems (Linux/Windows) and they all crashed. 
Must be a combination with another addon then.  Case closed i guess (no time to see which addon causes a conflict)

**Comment by onknight** [comment] 2021-01-06 12:11
> @onknight Videodevil has been working under matrix for over six months now
yes but uses  the Fusion repo no thanks ...

**Comment by Gujal00** [comment] 2021-01-06 13:01
@onknight Why would you install fusion repo?
Videodevil is the original adult addon from 2010 and has always been in xbmc-adult repo
I did the conversion to Matrix.
https://github.com/xbmc-adult/xbmc-adult

**Comment by onknight** [comment] 2021-01-06 19:29
I did Google search for addon and it only showed up in Fusion repo 
Thanks for Correction

**Comment by onknight** [comment] 2021-01-06 19:44
Been trying to find Repos names  from Github   so I can work on Kodi 19 Build

**Comment by TarkusLV** [comment] 2021-01-06 20:08
Love the new version.  Thanks for addressing the issues I raised!

**Comment by onknight** [comment] 2021-01-06 20:55
I made Portable Version of Kodi 19  so I can have 18 and 19 on the same PC 
would love to see my Free Cams added to the addon soon

**Comment by Gujal00** [comment] 2021-01-07 03:04
Myfreecams already added, will be in next release

**Comment by onknight** [comment] 2021-01-07 03:07
Very cool

**Closed** 2021-02-15 07:45 UTC
Labels: discussion
