### ISSUE TITLE
Xvideos not working 

### ISSUE THREAD

**Issue by mywayorhighway0** [dobbelina/repository.dobbelina#1134] opened 2023-07-28 05:00 UTC
### Bug reports:

On every link getting " oh ho could not find a supported link" no log file is produced for this error. Tried premium vpn with different options to no avail. No such issue on normal web browser and android app. Can you please check this?
### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment] 2023-07-28 05:58
Works for me on windows.
You need to make a log file.

**Comment by mywayorhighway0** [comment] 2023-07-28 06:15
Hey Dobbelina my friend, you need to believe me. It just says " oh ho" but no error or log file is given. Though, I m accessing this on Android TV box running android 10. Please trust me else kindly close the issue

**Comment by ErosVece** [comment] 2023-07-29 01:31
We believe you, providing the (DEBUG) log file is for us to see what the problem is. We don't have a crystal ball to see what the problem is at your side :)

**Comment by dobbelina** [comment] 2023-07-30 17:18
No log file, closing.

**Closed by dobbelina** 2023-07-30 17:18 UTC
