### ISSUE TITLE
My Freecams 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#267] opened 2020-08-06 15:33 UTC
I don't know what the thread was erased
But my free cams is still not working
Hoping we can get it fixed cuz it's one of the better cam sites on White cream

**Comment by frankee123** [comment] 2020-08-10 02:10
totally agree!

**Comment by dobbelina** [comment] 2020-08-13 06:05
Issue confirmed, thanks for reporting.

**Comment by onknight** [comment] 2020-08-13 12:04
I love the Addon  Just wish I could do more then report when things go down

**Comment by onknight** [comment] 2020-08-13 12:04
:)

**Comment by jdoedev123** [comment] 2020-08-15 00:43
MFC must have changed. They are breaking other packages such as streamlink. They are getting the same error UWC does (ValueError: invalid literal for int() with base 10: ''). 
From steamlink Issues:
[https://github.com/Damianonymous/streamlink-plugins/issues/6](url)
nadsugifka commented 25 days ago
Hello!
Mfc not record, error, please check and fix it
mfc-er

**Comment by onknight** [comment] 2020-08-15 02:50
so what can be done to fix it ?

**Comment by jdoedev123** [comment] 2020-08-15 03:53
The do not publish the API so someone needs to use a tool to reverse engineer the communications from a working camgirl webpage in a browser using a tool like the Chrome DevTools. The Python code then needs to be changed to communicate correctly.
I have taken a look and generally know whats happening this is not code I normally maintain.

**Comment by onknight** [comment] 2020-08-15 13:25
The been slowly Rewriting the code for Month  to Get rid of flash 
when Stated on site it was flash based and lot guys still used it 
now they don't

**Comment by jdoedev123** [comment] 2020-08-15 23:23
OnKnight, thanks that makes sense. I have not found any code on any open project which works with the new code.
I did find the code currently in UWC posted on a forum for another project. I am not sure if they borrowed from us or we borrowed from them. The point is that everyone has similar problems with the code changes at MFC and it is a matter of time before someone posts a solution. It may be us or it may be another project we borrow from.

**Comment by onknight** [comment] 2020-08-16 19:07
Question if someone where to go into private  is there a way to record  communications 
so we could get it working again

**Comment by jdoedev123** [comment] 2020-08-16 21:33
MFC is one of the more complicated communications protocols of all the supported websites.  I have dabbled on working on it over the years but have to start anew every few years to try to remember how the website works.
The current UWC code trys to communicate like the website through WebSocket but it looks like we are being an error message instead of data:
0 454557835 0 0 Guest6535800001933 0 454557835 1 0 00001933 0 454557835 1 0 00024830 1 454557835 0 0 {"_err":0,"ctx":[454557835,0,1,0,0,0,0,5325377],"ctxenc":"39a30dd26f%2FWzQ1NDU1NzgzNSwwLDEsMCwwLDAsMCw1MzI1Mzc3XQ%3D%3D","cx

That first 0 is enough to kill our code as it is unexpected. We are expecting to receive a bunch of messages with the CAMGIRLID and server etc but we get kicked instead.

**Comment by onknight** [comment] 2020-08-16 22:40
MFC a good site  But I think our not good now as Chatterbate or Camside cause they don't allow 
Couples on it unless they are women couples 
would love to have it back but as long we have the other two I am pretty happy

**Comment by dobbelina** [comment] 2020-08-23 21:14
Fixed in v.1.2.25, 
Thanks for the fix 12asdfg12 and welcome back!

**Comment by onknight** [comment] 2020-08-23 21:32
Can wait to try test it

**Comment by onknight** [comment] 2020-08-23 22:02
working great

**Comment by frankee123** [comment] 2020-08-24 01:35
You are a king! Ty

**Closed** 2020-08-25 05:57 UTC
Labels: fixed

**Comment by jdoedev123** [comment] 2020-09-16 23:05
Thanks 12asdfg12 for the fix. 
I have used your fix as a pattern to fix the streamlink plugin and plan to post it over at:
[Damiaanonymous Streamlink Plugins](https://github.com/Damianonymous/streamlink-plugins)
