### ISSUE TITLE
Daft sex

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#242] opened 2020-06-02 02:07 UTC
Daft sex just keeps crashing my device everytime click on something just freezes then kicks u out can u fix and datoporn won’t play anything and freeomovie not working can u sort please

**Comment by dobbelina** [comment] 2020-06-02 06:17
FreeOMovie confirmed broken.
Datoporn &  Daftsex works fine on my Windows rig.
What device and system are you on?

**Comment by deanogers** [comment] 2020-06-02 10:22
Firestick kodi 18.7 m8

**Comment by deanogers** [comment] 2020-06-02 18:26
Datoporn just keeps loading videos but won’t play them spins round but nothing works for some reason

**Comment by DJMix-I-Can** [comment] 2020-06-03 00:56
Datoporn & Daftsex works fine on my Windows & Android devices. At first, Daftsex didn't work on my Android device. I compared the settings and noticed that on my laptop under UWC general settings, Daftsex Resolver, I had it set to ResolveURL. Once I changed it to Internal (video resolution limited to 720P" it started working. When we have it set to ResolveURL, it tries to use the VK link which is no longer supported in the ResolveURL because VK now requires a log in. As for FreeOMovie, it's doesn't work for me either.

**Comment by 12asdfg12** [comment] 2020-06-03 12:38
Hi guys,
I'm having some real-life issues and I will not be able to submit fixes for some time.

Regarding daftsex, the internal option is more reliable but some videos won't play, and the resolution is limited to 720p.
The other option, ResolveUrl, works only with a premium account (tested with real-debrid) but right now vk.com is marked down on real-debrid webpage. Some videos still play from real-debrid cache.

**Comment by DJMix-I-Can** [comment] 2020-06-03 12:43
@12asdfg12 Hope all is well with you & yours. Hope everything works out for you. Life & health first!!!!

**Comment by dobbelina** [comment] 2020-06-03 20:12
Hi 12asdfg12 !

Thanks for the update of your status, I also wish you well in every aspect.
Please take care of yourself! :heart:
The community will always be here once you got your issues sorted.

**Comment by john12345670** [comment] 2020-06-07 20:15
deanogers: 

I have no problems with freezing or being kicked out of the app. 

Try to download one of the "wizard apps" to clean your cache, downloaded apps and thumbnails folder. 

Recommend "The Crew Wizard" as it's currently the newest and most updated one. It's available on "The Crew Repo". Google will show you how to add the repo on your firestick. 

Although I would recommend getting something more appropriate to run your streaming on. 

Something like the A95 Max, it has 4GB of ram and it has 64GB of flash storage plus you can add your own (up to 2TB) 2.5 inch Hard Drive into it for even more storage. 

The (Quad core) processor is very strong on this device and I have no problems with lagging menus or navigation. I'm running mine from a 500GB 2.5 inch 7200 RPM HDD and this is plenty of storage for the thumbnails. So I don't need to use the cleaning wizards that often if at all.

It doesn't cost that much more than a firestick if purchased from a Chinese online store. Good luck.

**Comment by jdoedev123** [comment] 2020-06-07 21:39
John12345780 and Deanogers,
I have some experience Developing on Android and have used a number of Android devices with with UWC on Kodi. (Currently a faulty HDMI cable fried my Amazon Fire TV and Nvidia Shield TV).
A frequent problem I had with UWC is it creates a massive cache of thumbnails over time which can overrun some Android devices limited Memory.
One little known trick I used to use was changing the data location for Android  [https://kodi.wiki/view/HOW-TO:Change_data_location_for_Android](url)
Basically a file (xbmc_env.properties) is put in the root directory of the Android device pointing to extra memory like a SD card with a one line command ( xbmc.data=<path to the Kodi data folder you wish to use>) This worked for the Nvidia Shield and a Samsung Tablet but I could never get it to work on an unrooted Amazon Fire. 
I really miss the Nvidia Shield TV as it had by far the best graphics processor on an Android device and the Nvidia X1 based ARM chip is miles ahead of the Amlogic S905X2 based Chinese Android boxes like the A95 Max. This led to very little "spinning" while loading and time outs.

**Comment by john12345670** [comment] 2020-06-09 05:22
Jdoedev123

I agree, the Nvidia Shield is currently the king of streaming boxes and especially the 2015 pro model with the 500GB HDD, but the pro model cost an arm and a leg. Where as the A95 Max is a poor mans Nvidia Shield Pro. 

I have a Nvidia Shield and quite honestly I don't notice any speed improvements (navigation wise) between the Nvidia's Tegra X1 and Amlogic S905X2 they both feel snappy. I don't game on these boxes but I strongly suspect the Shield will beat out the A95 Max on gaming.

I have had experience with the (2012) Firestick and the only thing it had going for it is the bluetooth remote control. I find the navigation in Kodi very laggy and playback choppy. My crappy old T95 android box did better job.

The reason I bought the A95 Max is precisely because of what you said. The thumbnails just grows and grows until you have to delete them otherwise it messes up your device. With a hard disk installed I don't have to worry about storage or worry about ware and tear on the flash memory. The processor upgrade is a nice bonus too.

Although my A95 box didn't came with the built in cooling fan, Kodi is run from the hard disk and it's perfect for my use and so far I'm very happy with it. 

Your solution on moving the data folder to external storage is great! I believe it's possible to move installed apps on Android (5 or is it 6? I don't remember) you just go to app manager and change from internal storage to SD card, or in my case the internal HDD. You don't need to edit the storage path for Kodi.

It sucks that your Shield died on you, I hurt just thinking about it. But the A95 Max is a good inexpensive streaming box. I can recommend it for streaming 100%, just don't buy it from reseller on ebay or Amazon they jack up the price quite a bit.

Anyway, thanks to all you wonderful people providing fixes for the addon. It is very much appreciated!

**Comment by jdoedev123** [comment] 2020-06-09 20:04
John12345670,
Nice counter point. The reason I mentioned the memory trick is on many Android devices, even if you move the App to external memory the cache still stays in the root memory unless you use the trick.

**Comment by john12345670** [comment] 2020-06-27 18:49
jdoedev123,

A little update, the A95X Max gives you two option when you go to storage. On the normal storage option it lets you format the HDD as system storage. if you choose this, apps will be installed to the HDD and the cache folder is located there too. So no need to add the xbmc_env.properties file to the root storage. If you go to the advance settings and then to storage it'll let you format the HDD as a external SD storage device. If you use this option, you'll have to add the xbmc_env.properties file to the root and specify where the cache folder should be located.

I found this out when I was messing around with the xbmc_env.properties file on my device. Long story short I had to rebuild my Kodi as I messed it up. But I hope this is useful to someone.

Also, I want to let people know that the missing fan header plug on the motherboard is not connected to the power. So if you are thinking of buying a fan and soldering it to the connection pads, it won't work! I've tried. Save yourself some grief.

All the best.

**Closed** 2020-11-10 22:31 UTC
Labels: discussion
