### ISSUE TITLE
Webcam shows  and chaturbate

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#853] opened 2022-09-14 10:35 UTC
### Bug reports:

Hello

Webcam shows is not working.
Chaturbate is slow for open videos sometimes is freeze

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by Gujal00** [comment] 2022-09-14 21:25
> Webcam shows is not working.

Duplicate of #844 site is gone, so needs to be removed from cumination

> Chaturbate is slow for open videos sometimes is freeze

Any bugreports without logfile will be deleted

**Comment by dobbelina** [comment] 2022-09-16 08:09
Webcam shows has been removed  https://github.com/dobbelina/repository.dobbelina/commit/c4da3a9643cb74d77cfbf55d897e1ca7c38fdb3e

**Comment by jegfonseca** [comment] 2022-09-16 08:13
Thanks

**Closed** 2022-09-25 06:12 UTC
Labels: fixed

**Comment by jegfonseca** [comment] 2022-09-25 09:04
Thanks
