### ISSUE TITLE
Can you add Xnxx?

### ISSUE THREAD

**Issue by Dbears0520** [dobbelina/repository.dobbelina#628] opened 2021-10-30 16:59 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**

**Comment by xerel89** [comment] 2021-10-31 04:04
Hope for add

**Comment by Gujal00** [comment] 2022-01-10 21:53
what is the url of the site?

**Comment by Dbears0520** [comment] 2022-01-10 22:15
Www.xnxx.com

**Comment by dobbelina** [comment] 2022-03-10 06:54
Will be in the next release 1.1.36 https://github.com/dobbelina/repository.dobbelina/commit/e9655c8b11108a630741efcb249e1f6c3e37961e

**Comment by dobbelina** [comment] 2022-03-13 07:41
Pagination seems a little short?

**Comment by Gujal00** [comment] 2022-03-13 23:13
Which section? the default page it opens 'todays-selection' is always only 5 pages long, you can compare on the site

**Comment by dobbelina** [comment] 2022-03-14 07:44
Sorry I mean there are to few videos per page.
On the first page i get 5 videos and on page 2 only 3 videos.
<img width="500" alt="screenshot00000" src="https://user-images.githubusercontent.com/46063764/158126779-d2f04030-893b-4689-8fb0-2a168195aa85.png">

**Comment by Gujal00** [comment] 2022-03-14 07:53
That is weird, I am getting 48 videos per page
![image](https://i.imgur.com/xbne1ue.png)

**Comment by dobbelina** [comment] 2022-03-14 08:14
I get the same 5 videos on both kodi 18.9 and 19.4 portable.
Could it have to do with the sites language and content settings?
You get different videos on todays selection if you change content country.
![bild](https://user-images.githubusercontent.com/46063764/158131475-f0b2eca5-dd99-46b7-a4fa-d41ee29d52ab.png)

**Comment by Tyke101** [comment] 2022-03-14 08:37
I can confirm the problem.
If you search for a word that would give many results you get just a few per page (usually just 1 to 4). 
It might say page 1 if 50 or page 1 of 132 but the next page button never gets beyond page 8.  It just alternates between pages 7 and 8 for ever.
This is using Nvidia Shield, android tv 9.0.1 and Kodi 19.3.

**Comment by Gujal00** [comment] 2022-03-14 11:05
> Here is the source code with Swedish language set for both language and content https://paste.kodi.tv/ayuyupowab Page https://www.xnxx.com/todays-selection
With that contents the regex in List section still catches 48 videos

https://regex101.com/r/omQZL9/1

Dont understand why it is only showing 5

**Comment by Gujal00** [comment] 2022-03-14 11:34
> I can confirm the problem. If you search for a word that would give many results you get just a few per page (usually just 1 to 4). It might say page 1 if 50 or page 1 of 132 but the next page button never gets beyond page 8. It just alternates between pages 7 and 8 for ever. This is using Nvidia Shield, android tv 9.0.1 and Kodi 19.3.

Yes. pagination not working beyond page 8 is a bug and will be fixed in the next release

**Comment by 12asdfg12** [comment] 2022-03-14 14:16
The problem is caused by UA, with some UAs, the resolution is not displayed.

'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0'
![image](https://user-images.githubusercontent.com/48175015/158189993-7663e846-969e-4a52-8aae-abba3587ad1a.png)

'Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko'
![image](https://user-images.githubusercontent.com/48175015/158189267-6bbab3c4-e9c4-4067-842d-15d6bc1c462d.png)

**Comment by Tyke101** [comment] 2022-03-14 18:38
Done a bit more research.  I have a few Nvidia Shields and as far as I can tell they are all set up identically.  Only 1 of them shows 4 or less videos per page, the rest work as expected and show full pages.
The 1 which has the problem strangely also lists mainly gay and trans videos.  I wondered if it was somehow being influenced by category settings in xHamster and xVideos but they are both set to straight.

**Comment by dobbelina** [comment] 2022-03-14 20:53
Will be fixed in the next 1.1.37 release https://github.com/dobbelina/repository.dobbelina/commit/c58d8a18d6d395659881244b7206a82fbfdc66b0

**Closed** 2022-03-20 06:51 UTC
Labels: fixed
