### ISSUE TITLE
[Bug] Porntrex Favorites shows only first page.

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#387] opened 2020-12-30 13:52 UTC
The following pages of the favorites always show the contents of the first page. Please fix it.

Thanks for your work!

**Comment by jdoedev123** [comment] 2021-01-02 22:01
To my knowledge, Favorites have always been one single (possibly large) page.

**Comment by Kodionpi** [comment] 2021-01-02 23:07
Thanks for your reply. The first page of porntrex favorites has 31 entries. It doesn't bother me how many entries each page has, but that the content is repeated over and over on each page. The first page (main page) of porntrex under UWC has 92 entries.

**Comment by jdoedev123** [comment] 2021-01-03 01:46
I am not quite sure of problem. I have noticed that it does matter how long you linger on a page or it may affect if some entries are repeated. I have always assumed this is a feature (not a bug) of how UWC uses the underlying webpage pagination and how frequently new content is added especially for PornTrex. It is literally like drinking out of a firehose.
This leads to the content sometimes changing between when you started paging through PornTrex on UWC and when you hit "Next". By that time new content may have come in pushing content onto later pages thus it looks like a repeat but it is correct for the underlying website.

**Comment by Kodionpi** [comment] 2021-01-03 09:41
Thank you for your reply! I'm a little confused as to what you're trying to tell me. :) I understand that content can move  to the back yet,- when new content is added. 

A comparison: 
Main page 
--> 92 entries, video 1 -92 (first page) 
--> 92 entries, video 93 -184 (second page) -different videos(!)
--> 92 entries, video 184 -273 (third page) -different videso (!)
--> and so on

Favorites 
--> 31 entries, video 1-31 (first page)
---> 31 entries, video 1-31 (second page) -same videos
---> 31 entries, video 1-31 (third page) - same videos

Let's assume I have 150 videos saved under favorites (unchanged for months). I will never be able to watch all of them, because I always see the same entries,- on every new page. Videos 1-31 ...the remaining 120 videos don't show up on any page, no matter how many times you turn the page and wait.

But yes, you are right, if I would also go the website and add new videos, then it would also reappear the first page under the videos 1-31 at the top.

The point is that under favorites, the "Next Page" button basically does nothing. On each page the same 1-31 videos are displayed. With no way to be able to see the subsequent videos.

**Comment by 12asdfg12** [comment] 2021-01-03 09:44
will be fixed in cumination

**Comment by Kodionpi** [comment] 2021-01-03 10:49
Thanks @12asdfg12 ! The problems I described above only affect the UWC version. Whether the problems also occur under cumination, I can not say. -because with cumination, I don't even get that far. Porntrex--> Login works but when I go to "Subscription videos" --> not a single video is shown. "It looks like the website is to slow" is displayed. -same on "manage subscriptions"

**Comment by 12asdfg12** [comment] 2021-01-03 10:55
Wait for the next version, 'favorites' are not implemented in the current version of cumination.
Regarding the 'website is too slow' issue, try logging off and on.

**Comment by ErosVece** [comment] 2021-01-04 15:41
Subscription videos in Porntrex is for when you subscribe to a pornstar/model, you can see all their videos there (like visiting https://www.porntrex.com/my/subscriptions/).
You can easily subscribe to a pornstar from contextmenu on a video (if it has their name added to the video).

**Comment by ErosVece** [comment] 2021-01-04 15:42
Future versions will have a models listing, so you can look up/subscribe to any model on there.

**Comment by Kodionpi** [comment] 2021-01-04 19:08
Thanks @ErosVece My mistake, I equated "subscription videos" with "favorites". At first I thought this meant access to https://www.porntrex.com/my/favourites/videos/

**Closed** 2021-01-12 19:05 UTC
