### ISSUE TITLE
Daftsex cumination 

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#512] opened 2021-05-15 19:27 UTC
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Hello

Addon cumination 

Dafsrex is not working for me

Why?

Thanks

**Comment by Gujal00** [comment] 2021-05-16 09:00
Duplicate of #481 
Will be fixed in the next release

**Comment by jegfonseca** [comment] 2021-05-16 09:02
Thanks you

**Closed** 2021-05-23 19:23 UTC
Labels: fixed
