### ISSUE TITLE
Cumination - Xtheatre

### ISSUE THREAD

**Issue by Pixelbruh** [dobbelina/repository.dobbelina#417] opened 2021-01-25 11:29 UTC
"Could not find a supported link" on both Windows and Firestick.

My apologies that I cannot myself provide a solution.

**Comment by Gujal00** [comment] 2021-01-27 00:02
It is not a bug, the recent videos are using a hoster (richioon which is an alias of waaw/netu/hqq) that cant be resolved by ResolveURL due to use of captcha. Older videos do not use that hoster and work fine

**Closed** 2021-03-10 22:48 UTC
