### ISSUE TITLE
Speedporn, no thumbnails

### ISSUE THREAD

**Issue by grntbggr** [dobbelina/repository.dobbelina#1461] opened 2024-11-29 18:55 UTC
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Speedporn hasn't shown Thumbnails in about a week.

### Kodi version

19.4

### Cumination version

1.1.120

### Operating System and version

Android

**Comment by Gujal00** [comment] 2024-11-29 19:01
Duplicate of recently fixed and closed #1457

**Comment by grntbggr** [comment] 2024-11-29 19:04
My mistake.  Forgot to check the log.  Thx

**Closed** 2024-11-30 17:44 UTC
