### ISSUE TITLE
repository.dobbelina needs to update

### ISSUE THREAD

**Issue by joseejohn4** [dobbelina/repository.dobbelina#124] opened 2019-11-08 13:37 UTC
chaturbate not working from last week can you look after please

**Comment by DJMix-I-Can** [comment] 2019-11-08 20:47
Chaturbate has been working for me but as of today, it's not working.

**Comment by dobbelina** [comment] 2019-11-09 07:07
Confirmed, broken.

**Comment by pitsi** [comment] 2019-11-09 11:22
It is a site issue. Youtube-dl also broke and can not parse any info.
https://github.com/ytdl-org/youtube-dl/issues/23010

**Comment by Buhric** [comment] 2019-11-10 15:11
Looks like they switched over to FLASH player... and no jsplayer anymore...
can someone fix ?

**Comment by DJMix-I-Can** [comment] 2019-11-10 15:13
It's already fixed, there's a pull request for it. It will get updated soon...

**Comment by psyco752** [comment] 2019-11-10 22:25
> It's already fixed, there's a pull request for it. It will get updated soon...
are you going to update the application soon? in the repository I don't see any new version.

**Comment by dobbelina** [comment] 2019-11-11 07:35
Is fixed by 12asdfg12  #125, thank you!

**Closed** 2019-11-12 18:37 UTC
Labels: fixed
