### ISSUE TITLE
Cumination / Xvideos

### ISSUE THREAD

**Issue by max834eiie** [dobbelina/repository.dobbelina#1422] opened 2024-09-25 10:54 UTC
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Xvideos doesnt work anymore. 

Error message: 
“oh oh could not find a supported link”

Firestick 4K 
Kodi 21.1
Culmination: 1.1.116

### Kodi version

21.1

### Cumination version

1.1.116

### Operating System and version

Firestick 4K

**Comment by Gujal00** [comment] 2024-10-20 02:10
Probably a region issue. Need logfile to see what the issue is

**Comment by dobbelina** [comment] 2024-10-25 16:14
Closing, no log file.

**Closed by dobbelina** 2024-10-25 16:14 UTC
