### ISSUE TITLE
2 different errors I have been getting

### ISSUE THREAD

**Issue by frankee123** [dobbelina/repository.dobbelina#877] opened 2022-11-04 00:20 UTC
### Bug reports:

I get an error trying to play anything in 4k using Spankbang. I also have a issue with Chaturbate girls that take a long time to load when I click on them from my favorites folder and playback will eventually fail. It will work clicking on them again, but obviously something is wrong. I hope I uploaded my kodi log correctly, sorry if I did not.

### OS environment
Android box version 11

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here-https://paste.kodi.tv/pimoqokiti

Any bugreports without logfile will be deleted.

**Comment by frankee123** [comment] 2022-11-04 00:24
I see numbers on the left of the kodi file and I can tell you it is line 1091 where I tried to click on a chaturbate girl and that is where I got the playback error if that helps at all.

**Comment by DJMix-I-Can** [comment] 2022-11-04 00:37
Ok, I took a quick peek at your debug file. There are conflicting reports about your box. In one page it states that it supports 4K resolution and according to this page the maximum resolution is [1080p.](http://deviceinfohw.ru/devices/item.php?item=239703) The debug file also states it on line 326. Have you actually successfully played a 4K file. If you play a 4K file, look in either Kodi info setting within the OSD or check your TV settings. Does your TV support 4K? Honestly, I think it's your box.

**Comment by frankee123** [comment] 2022-11-04 00:53
Thanks, yes my tv supports 4k and I can play 4k vids or scenes in other programs like Porntrex, it just seems to be spankbang that gives me the error from what I have found. Geez, I took a shot when I ordered this box as it just came out but there were no reviews. The specs seemed good and it says plays 4k. https://www.amazon.com/gp/product/B09ZTLJH3P/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
I have had terribl luck with numerous electronics in my life, and maybe this is just another one. Ugh, do you recommend any android boxes then bro?

**Comment by DJMix-I-Can** [comment] 2022-11-04 01:14
Funny you should mention that, there are two reviews & one of them said the same thing you said. It's from the same link you posted. You need to do more researching instead of just jumping on good deals. I've had a chinese box before, it did suffice for that time but then I started upgrading my setup, it couldn't support my setup. I did upgrade to a popular name brand but eventually got rid of it because of the constant ads they threw at me. Honestly, it all depends on what your setup is, what you're expecting & your budget.  I personally have three Nvidia Shields. The only one I bought brand new was the 2019 version. The other two are used & bought them on ebay. No problems at all with them BUT, I don't buy from just anyone. If they have less than 94% feedback or have only sold 2 or three items, I'll pass. I also look at their feedback. Research before you buy... If the price is to good to be true, it probably is.

**Comment by frankee123** [comment] 2022-11-04 01:30
I hear ya, it wasn't a great deal or anything, it was just a box that was brand new and the specs were better than the old box I had. I don't know what to think as any other 4k vid plays on cumination, just not spankbang. I went to youtube and played a 4k video as well.

**Comment by DJMix-I-Can** [comment] 2022-11-04 01:39
Well 45 bucks for it is a deal compared to the Shield. You were better off getting an Amazon 4K Max Pro... Even though I don't support Amazon products. I'm just looking at budget wise. The reason why I stated to look at the video info on your TV or Kodi while playing a "4K" file was because I have an older TV that only supports 1080p. I'm able to play 4K files but it's down scaled. That's why I stated that.

**Comment by frankee123** [comment] 2022-11-04 01:45
I think it was like $60 or something like that when I bought it, could have been worse lol. Yea, I got a Vizio 4k tv 2 years ago on sale. Anyways, I really appreciate your insight and help. Maybe somebody can figure something out for me lol. If not, I'll probably just reinstall kodi all together I guess.

**Comment by DJMix-I-Can** [comment] 2022-11-04 01:53
Ok, I don't feel like you're understanding but ok. Good luck...

**Comment by frankee123** [comment] 2022-11-04 02:04
I just meant maybe somebody could figure something out about the errors in my kodi log is all. Not sure what you mean for not understanding bro. I understand what you mean about the 4k but they play and definitely look 4k, and they also do on youtube.

**Comment by 12asdfg12** [comment] 2022-11-04 16:58
The error with the 4k spankbang videos will be fixed in the next release.

**Comment by frankee123** [comment] 2022-11-04 22:38
Thanks, do you know any reason why sometimes clicking on the chaturbate girls won't play and the playback failed comes up? Did the kodi log I posted show anything about it or no?

**Comment by 12asdfg12** [comment] 2022-11-05 11:21
No, I can not reproduce the error on my Kodi setup and I have no idea what causes the error from the log file.

**Comment by frankee123** [comment] 2022-11-05 14:09
Ok, no worries. Thx for the reply friend.

**Closed** 2022-11-06 09:24 UTC
Labels: fixed
