### ISSUE TITLE
Chatturbate crashes using Android 10

### ISSUE THREAD

**Issue by net121** [dobbelina/repository.dobbelina#147] opened 2019-12-20 00:09 UTC
Anyone noticed that issue? Tested on 3 different oneplus 7 pro and oneplus 7t. I don't have this problem with Android pie.

**Comment by DJMix-I-Can** [comment] 2019-12-21 04:48
So, I whipped out my old Samsung Note 3 and flashed Android 10 on it. I can confirm that on Android 10, Chaturbate, BongaCams, Camsoda & Cam 4 crash when it's just about to play (creating demuxer). MyFreeCam & Streammate do not crash. @net121 did you also post this problem on the [Kodi forum](https://forum.kodi.tv/showthread.php?tid=350235) What I noticed between all the cam py files is that streamate & myfreecam use websocket. If anyone is interested on the debug files with the extra components enabled like Kodi forum suggested, I could provide it. @net121 if someone asks for the debug files, I don't think you'll be able to provide them in the Kodi forum.

**Comment by net121** [comment] 2019-12-21 19:30
Whitecream addon in banned on kodi forum. They removed my post.

**Comment by net121** [comment] 2019-12-21 19:33
I wish someone could fix this issue. I have another streaming addon which crashes on Android 10. That's really sucks...

**Comment by net121** [comment] 2019-12-27 23:43
Please fix the issue !!!!

**Comment by 12asdfg12** [comment] 2019-12-29 10:48
I don't have any android devices with kodi and my phone is only android 9, so i can't reproduce the issue. At least post some log/debug info.
Have you tried to change the Playback mode in settings (i'am not sure if these still works but worth a try)?

**Comment by net121** [comment] 2019-12-29 14:04
Thank you so much.
Someone posted here a log but I guess he removed a post. I will try reproduce an error. It's going to be hard because I went back to Android 9.
But I really like 10.

**Comment by net121** [comment] 2020-01-01 04:45
I don't know how to attach log file on website

**Comment by net121** [comment] 2020-01-01 04:46
How to attach a log?

**Comment by 12asdfg12** [comment] 2020-01-01 18:07
It seems to be a Kodi issue, the url looks good and Kodi crashes after the playback begins.
Here is attached a version for chaturbate.py that uses a different function for playback.
[chaturbate.zip](https://github.com/dobbelina/repository.dobbelina/files/4014365/chaturbate.zip)

 Replace chaturbate.py from uwc addon with this file. chaturbate.py is located in the "plugin.video.uwc/resource/lib/sites/" folder.
With this version, try playing a video using the "play from here" option in the context menu. You should see a "test VERSION" notification.
If that doesn't work, i can't fix it.

the context menu:
![image](https://user-images.githubusercontent.com/48175015/71644510-2bee1900-2cd2-11ea-8cee-aead7afba717.png)

the notification:
![image](https://user-images.githubusercontent.com/48175015/71644515-4de79b80-2cd2-11ea-9073-bf41c8ba65be.png)

**Comment by net121** [comment] 2020-01-01 20:05
Thank you for trying. Unfortunately crashes again.

**Comment by 12asdfg12** [comment] 2020-01-02 09:37
You can prove that it is not an addon problem.
Look in the log file for the direct link which cause the crash.

This is an example for chaturbate (from kodi.log):
`VideoPlayer::OpenFile: https://edge137.stream.highwebmedia.com/live-hls/amlst:wetdream111-sd-65337ec998a49bc745363bd69848561dc1c54a15d9f1b151c0f184c2a9d3269d_trns_h264/playlist.m3u8|verifypeer=false.`
The direct link is:
`https://edge137.stream.highwebmedia.com/live-hls/amlst:wetdream111-sd-65337ec998a49bc745363bd69848561dc1c54a15d9f1b151c0f184c2a9d3269d_trns_h264/playlist.m3u8`

Create a file with .strm extension and put the link in the file.
Open the file in Kodi, in VIDEOS/Files menu and probably Kodi will crash.
But you cannot use chaturbate links to report the error, because the link dies when the performer goes offline, you need to find links which works all the time (live camera feeds, live tv...) and cause the crash.

**Comment by net121** [comment] 2020-01-02 17:50
My friend I know you are right.... They won't let me talk about chatturbate on kodi forum because I will be banned. 
I know that you did the best to make this work on Android 10, however Android 10 is not compatible with kodi and that's why we do have those crashes.


I would like to know if chatturbate is m3u8 stream?

**Comment by 12asdfg12** [comment] 2020-01-03 12:33
yes, the stream is m3u8

**Comment by net121** [comment] 2020-01-03 22:20
Thank you.
Looks like all m3u8 streams are affected.

**Comment by net121** [comment] 2020-01-05 22:32
Just FYI this is discussion about this issue.
https://forum.kodi.tv/showthread.php?tid=350235

**Comment by frankee123** [comment] 2020-01-18 22:42
Is there any fix? It sucks trying to watch any girl and it constantly freezes and buffers.

**Comment by net121** [comment] 2020-01-18 22:48
Looks like your internet sucks.
Chatturbate works perfectly on Android 7, 8 and 9. Crashes kodi using Android 10.

**Comment by frankee123** [comment] 2020-01-19 15:35
Yea that must be it. Coming from the guy who made the original post about it crashing...smfh

**Comment by thehutt61** [comment] 2020-05-02 19:17
This issue will be fixed in Kodi v18.7... meanwhile you can download the latest release of Kodi Nightly to fix the issue.

**Closed** 2020-10-09 05:46 UTC
