### ISSUE TITLE
Latest version 1.1.3 -- addon does not start anymore

### ISSUE THREAD

**Issue by atreyuhere** [dobbelina/repository.dobbelina#404] opened 2021-01-12 15:36 UTC
Since the latest update, starting the addon generates an error. Revert to 1.1.1 and all is fine.

**Comment by TarkusLV** [comment] 2021-01-12 15:50
I installed the update on three different devices.  On all three, I had to install it twice, because after the first time it would produce an error when trying to open.  After installing it again (same version), it works fine.  Probably has to do with the new addon that's installed in the update.

**Comment by JulGer** [comment] 2021-01-12 23:20
Tried the multiple install method. No dice. Will not open.

**Comment by Gujal00** [comment] 2021-01-13 01:49
cant do anything without a debug log

**Comment by 12asdfg12** [comment] 2021-01-13 05:16
I think the crash is caused by the new dependency, common.plugin.cache.
I tried a new installation from the repository and common.plugin.cache was not installed. However, when installing from the zip file, de dependency was installed.

Try to manually install the common.plugin.cache add-on from the kodi repository / services.

**Comment by bizznatch** [comment] 2021-01-13 06:17
Had the same issue, manually installing common.plugin.cache from the kodi repository fixed the problem for me

**Comment by atreyuhere** [comment] 2021-01-13 06:56
Reinstalling unfortunately does not fix it here

**Comment by JulGer** [comment] 2021-01-13 09:12
Thanks 12asdfg12.
That did it for me. Works fine again.

**Comment by Gujal00** [comment] 2021-01-13 10:27
@dobbelina 
the addon.xml in the plugin zip folder is correct and has script.common.plugin.cache listed
```
<addon id="plugin.video.cumination" name="Cumination" provider-name="Cumination" version="1.1.3">
    <requires>
        <import addon="script.module.six" />
        <import addon="script.module.kodi-six" />
        <import addon="script.module.resolveurl" version="5.0.00" />
        <import addon="script.module.resolveurl.xxx" version="2.0.1" />
        <import addon="script.common.plugin.cache" />
        <import addon="script.module.websocket" version="0.50.0" />
        <import addon="script.module.requests" optional="true" />
    </requires>
```
however the repository addons.xml is missing the dependency. can you correct it please, it is is causing install issues

```
<addon id="plugin.video.cumination" name="Cumination" provider-name="Cumination" version="1.1.3">
    <requires>
        <import addon="script.module.six" />
        <import addon="script.module.kodi-six" />
        <import addon="script.module.resolveurl" version="5.0.00" />
        <import addon="script.module.resolveurl.xxx" version="2.0.1" />
        <import addon="script.module.websocket" version="0.50.0" />
        <import addon="script.module.requests" optional="true" />
    </requires>
```

**Comment by dobbelina** [comment] 2021-01-13 22:32
@Gujal00 
Ahh, i missed that.
Has been fixed now.

**Closed** 2021-01-14 15:58 UTC
