### ISSUE TITLE
HQPorner doesn't playback

### ISSUE THREAD

**Issue by BobBarnes010** [dobbelina/repository.dobbelina#1261] opened 2024-01-22 13:19 UTC
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Hello,

HQ Porner seems to be broken for around a week.

Site availability seems fine as well as thumbnail/video indexing/resolution selector but when you start to play any video, playback failed with the usual "One or more items failed to play..."
I tried to sample different videos and resolution, all failed.

Steps to reproduce : 
- Browse to HQPorner
- Try to open up any video

### Kodi version

20.2

### Cumination version

1.1.98

### Operating System and version

OSMC 2023.12-1 Build

**Comment by Gujal00** [comment] 2024-01-22 21:14
duplicate of the already fixed #1255

**Closed** 2024-01-23 07:33 UTC
