### ISSUE TITLE
Add-On Compatibility with Kodi 20 "Nexus" [Android] 

### ISSUE THREAD

**Issue by RFL0WGitPR** [dobbelina/repository.dobbelina#905] opened 2022-11-27 01:15 UTC
***//Issues***

Kodi 20 (Nexus) is currently on its Beta phase and recently starting to release on the Google Play Store for Beta Insider and early adopters. Please if you would kindly consider testing and optimizing compatibility Add Ons such as Cumination video add on and the Dobbelina Repo for Kodi 20 (Nexus) 

It currently fails to launch successfully on this build there's no error message prompt

It's just doesn't work with Kodi 20 Beta 1 

Does not launch or open when selected on the Kodi Menu
No previews of the addon app or modules
No error prompts 

***Affected Adds Ons*** 

Repo Origin 
THE CREW REPO

- dobbelina repo 1.0.3 
- Video Add-On Cumination 1.1.58

***//Why apply these changes***

Kodi 20 "Nexus" is the next major release and their will be a lot of demand for it since Kodi is multiplatform will be nice if the Add-Ons and Repo is already optimized ready and compatible to work with next major build multiple platforms would benefit using your add-ons.

I hope the development team can consider this feedback for future updates early Kodi adopter and Android users will be very happy

Thank you

***//My Device specs***

Kodi ver. 20 Beta 1 "Nexus" APK [Git]
Platform: Android TV 9 (Pie)
Device : TCL Model - 50S434 [4K UHDTV - HDR].
CPU: 4x ARM Cortex-A55 @ 110 MHz 64-bit ARMv8-A (32-bit mode)
Screen Resolution: 1920 x 1080p (45/45 dpi)
GPU: Mali-470 MP (OpenGL ED 2.0 35f8d2d).
RAM: 2GB "2048MB"

**Comment by onknight** [comment] 2022-11-27 02:27
I been testing on 20 for 2 Months on two builds and it works fine

**Comment by Gujal00** [comment] 2022-11-27 21:34
Cumination works fine on Kodi20, however the repo needs an update to handle Kodi20. @dobbelina

**Comment by dobbelina** [comment] 2022-11-28 05:52
@Gujal00 
Is it the dir tag that needs modification?
https://github.com/croneter/repository.plexkodiconnect/pull/3

**Comment by Skates1616** [comment] 2022-11-28 06:12
This is one of the error messages in the log:

`2022-11-28 00:03:02.444 T:8693    error <general>: Repository add-on repository.dobbelina uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.`

And there is something going on with the Addon and Beta 1 of Nexus 20, it will not launch here, I get the following error in the Kodi log:

```
2022-11-28 00:06:28.666 T:4434     info <general>: CActiveAESink::OpenSink - initialize sink
2022-11-28 00:06:28.666 T:4434     info <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2022-11-28 00:06:28.685 T:4434     info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 56720 m_frames: 1418 m_frameSize: 8 channels: 2
2022-11-28 00:06:31.911 T:4067    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2022-11-28 00:06:32.893 T:8917    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'getargspec' from 'inspect' (/mnt/expand/1d59f1e0-a4a7-4c35-b19a-49eae5eebd17/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/inspect.py)
                                                   Traceback (most recent call last):
                                                     File "/storage/8A09-1F01/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.video.cumination/default.py", line 28, in <module>
                                                       from resources.lib.url_dispatcher import URL_Dispatcher
                                                     File "/storage/8A09-1F01/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.video.cumination/resources/lib/url_dispatcher.py", line 19, in <module>
                                                       from inspect import getargspec
                                                   ImportError: cannot import name 'getargspec' from 'inspect' (/mnt/expand/1d59f1e0-a4a7-4c35-b19a-49eae5eebd17/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/inspect.py)
                                                   -->End of Python script error report<--
                                                   
2022-11-28 00:06:32.970 T:8916    error <general>: GetDirectory - Error getting plugin://plugin.video.cumination/
2022-11-28 00:06:32.980 T:4067    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/) failed
```

**Comment by dobbelina** [comment] 2022-11-28 10:12
@Skates1616 
Try this modified repository file and test again.
[repository.dobbelina-1.0.3-test.zip](https://github.com/dobbelina/repository.dobbelina/files/10102624/repository.dobbelina-1.0.3-test.zip)

**Comment by Kaveon2022** [comment] 2022-11-28 14:08
Hey. I can confirm that the add-on fails to launch on the new beta 1... Worked fine on alpha 3 though.

**Comment by Kaveon2022** [comment] 2022-11-28 14:13
Getting this error... ImportError: cannot import name 'getargspec' from 'inspect'

**Comment by onknight** [comment] 2022-11-28 14:54
it installed for me But dose not show up in the addons

**Comment by RFL0WGitPR** [comment] 2022-11-28 16:21
Thank you kindly I'll manually install the repo from the zip and test the add-ons to see if it works 📦🗂️⚙️🧰📺

**Comment by Gujal00** [comment] 2022-11-28 18:35
Most of the issues reported here could be because of Kodi on Android as they changed the python version to 3.11 https://github.com/xbmc/xbmc/commit/1f61ce445abaaeaa5c27bb48413d2c5c40671354, no issues on Windows as it is still on Python 3.8.15 and works fine.
It is weird that Team Kodi refuse to update Python on Windows but will do it for Android even though they are the ones bundling Python with kodi for both platforms.
None of the devs use Android platform for addon development so cant do a thing about it

**Comment by onknight** [comment] 2022-11-28 23:36
> > @Skates1616 Try this modified repository file and test again. [repository.dobbelina-1.0.3-test.zip](https://github.com/dobbelina/repository.dobbelina/files/10102624/repository.dobbelina-1.0.3-test.zip)
> 
> The repo error is fixed, now the only error left is this one, it prevents the addon from launching on Kodi 20 Beta 1:
> 
> ```
> `2022-11-28 09:00:39.888 T:32566   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'ModuleNotFoundError'>
>                                                    Error Contents: No module named 'six'
>                                                    Traceback (most recent call last):
>                                                      File "/storage/14E3-1CEA/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.video.cumination/default.py", line 23, in <module>
>                                                        import six
>                                                    ModuleNotFoundError: No module named 'six'
>                                                    -->End of Python script error report<--
>                                                    
> 2022-11-28 09:00:39.937 T:32565   error <general>: GetDirectory - Error getting plugin://plugin.video.cumination/
> 2022-11-28 09:00:39.946 T:32273   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/) failed`
> ```

**WORKING NOW !**

**Comment by dobbelina** [comment] 2022-11-29 07:59
Repo updated to repository.dobbelina-1.0.4
Nexus compliant dir tags
https://github.com/dobbelina/repository.dobbelina/commit/55432527c351800e456445e4e61ef3942bd2694c

**Comment by ErosVece** [comment] 2022-11-29 08:05
People with getargspec error, can they try this?

Edit this file, url_dispatcher.py on your device (https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/url_dispatcher.py)

Line 19, change it to
`from inspect import getfullargspec as getargspec`

And see if that works.

**Comment by Skates1616** [comment] 2022-11-29 15:12
> People with getargspec error, can you try this?
> 
> Edit this file, url_[dispatcher.py](http://dispatcher.py) on your device (https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/url_dispatcher.py)
> 
> Line 19, change it to `from inspect import getfullargspec as getargspec`
> 
> And see if that works.

That did not work. 

I get the following error in the Kodi log:

```
022-11-29 09:10:50.578 T:32273   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2022-11-29 09:10:50.871 T:19188   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'six'
                                                   Traceback (most recent call last):
                                                     File "/storage/14E3-1CEA/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.video.cumination/default.py", line 23, in <module>
                                                       import six
                                                   ModuleNotFoundError: No module named 'six'
                                                   -->End of Python script error report<--
                                                   
2022-11-29 09:10:50.915 T:19187   error <general>: GetDirectory - Error getting plugin://plugin.video.cumination/
2022-11-29 09:10:50.925 T:32273   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/) failed
2022-11-29 09:10:53.887 T:32273    info <general>: CWinSystemAndroid::DestroyWindow
```

**Comment by ErosVece** [comment] 2022-11-29 15:28
Well, my fix works for the first error.

Now there is a new error, it looks like that Six is also removed from Python 3.11 or something.
We'll have to investigate this further.

**Comment by Skates1616** [comment] 2022-11-29 16:10
> script.module.six

You are correct, reinstalled the six module and it worked!

The change to Line 19 above is the fix for Nexus.

**Comment by ErosVece** [comment] 2022-11-29 16:24
Cool, enjoy the content on Nexus :)

**Comment by Skates1616** [comment] 2022-12-01 04:12
> Repo updated to repository.dobbelina-1.0.4
> Nexus compliant dir tags
> [5543252](https://github.com/dobbelina/repository.dobbelina/commit/55432527c351800e456445e4e61ef3942bd2694c)

You can include @ErosVece fix, it works.

**Comment by dobbelina** [comment] 2022-12-03 07:25
Fixed url_dispatcher.py will be in the next release v1.1.59 https://github.com/dobbelina/repository.dobbelina/commit/00cbe347bc671a51798ea39f7d43b3d0199373ff#diff-9fa1f8d01c3279aa21a1a16e365f9d5055a62132a319dd6ce094ccfd366ab565

**Comment by RFL0WGitPR** [comment] 2022-12-03 07:36
Thanks to everyone all Dev teams for taking your time to troubleshoot debug / tweak & fix these compatibility issues Kudos / Props to you all 👍👏👏

**Closed** 2022-12-09 18:38 UTC
