### ISSUE TITLE
Porngo and porn00 

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#464] opened 2021-03-16 13:30 UTC
Don’t play any videos tried lots on both just keep getting video failed to play can u fix

**Comment by dobbelina** [comment] 2021-03-16 17:52
Works fine in windows, both cumination and UWC.

**Comment by jp194978** [comment] 2021-03-17 02:03
when i try to play a video, on porngo and porn00 i get the following message, play back failed one or more items failed to play check the log for more information about this message, where can i check the log..Thank you

**Comment by dobbelina** [comment] 2021-03-17 21:52
> 
> 
> On cumination,when i try to play a video, on porngo and porn00 i get the following message, play back failed one or more items failed to play check the log for more information about this message, where can i check the log..Thank you

https://howtomediacenter.com/en/how-to-check-kodi-log-file/
Logfile with debugging enabled can be uploaded here:
https://paste.kodi.tv/

What platform are you running kodi on?
What version of kodi are you running?

Without this information it's impossible to pinpoint the cause of the issue.

**Comment by jp194978** [comment] 2021-03-17 21:55
Windows  10 /  Kodi 19 Matrix

**Comment by deanogers** [comment] 2021-03-18 08:53
Kodi 19 matrix on firestick 4K

**Comment by jp194978** [comment] 2021-03-23 02:00
porngo and porn00 working fine now on windows 10 thank you

**Comment by dobbelina** [comment] 2021-03-24 07:18
I don't see any issue on Win 10 as well, closing issue.
Without a logfile it's impossible to pinpoint what might be causing any issues
on other platforms.

**Closed by dobbelina** 2021-03-24 07:18 UTC
